---
- name: Turn on HTTPS encryption for Splunk Web using the web.conf
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/web.conf"
    section: "settings"
    option: "enableSplunkWebSSL"
    value: "true"
    mode: 0644
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
  become: true
  notify: restart splunk
