---
- debug:
    msg: "The splunk_package_url is set to: {{ splunk_package_url }}"

- debug:
    msg: "The filename that will be downloaded is {{ splunk_file }}"

- debug:
    msg: "The upgrade file will be downloaded to {{ splunk_package_path }}/{{ splunk_file }}"

- name: "Download Splunk {{ splunk_install_type }} package"
  become: "{{ splunk_download_local | ternary( false, true ) }}"  # true == false; false == true
  get_url:
    url: "{{ splunk_package_url }}"
    dest: "{{ splunk_package_path }}/{{ splunk_file }}"
  delegate_to: "{{ splunk_download_local | ternary('localhost', omit) }}"
  register: download_result
  retries: 3
  delay: 10
  until: download_result is success
  run_once: "{{ splunk_download_local }}"

- name: "Unarchive Splunk {{ splunk_install_type }} package to {{ splunk_home }}"
  unarchive:
    src: "{{ splunk_package_path }}/{{ splunk_file }}"
    dest: "{{ splunk_install_path }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    remote_src: "{{ splunk_download_local | ternary( false, true ) }}"  # true == false; false == true
  become: true
  notify:
    - start Splunk

- name: Check if splunk-launch.conf.bak exists
  stat:
    path: "/opt/splunk/etc/splunk-launch.conf"
  register: splunk_launch_orig

# splunk 9.3 quickfix> permissions denied on startup
- name: Set permissions on splunk-launch.conf
  file:
    path: "/opt/splunk/etc/splunk-launch.conf"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: '0640' 
  when: splunk_launch_orig.stat.exists

- name: Check if splunk-launch.conf.bak exists
  stat:
    path: "/opt/splunk/etc/splunk-launch.conf.bak"
  register: splunk_launch_bak

- name: Set permissions on splunk-launch.conf.bak if it exists
  file:
    path: "/opt/splunk/etc/splunk-launch.conf.bak"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: '0640'
  when: splunk_launch_bak.stat.exists


- name: "Remove {{ splunk_package_path }}/{{ splunk_file }} package"
  become: true
  file:
    path: "{{ splunk_package_path }}/{{ splunk_file }}"
    state: absent
  when: not splunk_download_local
