---

- name: "Wait for indexer-status to become green"
  uri:
    url: "https://{{ item }}:8089/services/server/health/deployment/details?output_mode=json"
    user: "{{ splunk_admin_username }}"
    password: "{{ splunk_admin_password }}"
    validate_certs: no
    return_content: yes
  delegate_to: "{{ groups['clustermanager'] | first }}"
  debugger: on_failed
  register: response
  retries: 100
  timeout: 10
  delay: 10
  until: 
    - response.json is defined
    - 'response.json.entry[0].content.features.splunkd.indexer_clustering.data_searchable.health == "green"'
    - 'response.json.entry[0].content.features.splunkd.indexer_clustering.peer_connectivity.health == "green"'
    - 'response.json.entry[0].content.features.splunkd.indexer_clustering.indexing_ready.health == "green"'
  with_items:
    - "{{ groups['clustermanager'] | first }}"