# Example playbook to install Splunk and configure a basic indexer cluster
# Ensure that the following vars are configured: ansible_user, ansible_ssh_private_key_file, splunk_uri_lm, and splunk_admin_password
- hosts:
    - clustermanager
    - indexer
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: check_splunk.yml
  vars_files:
    - ../environments/vault.yml


- hosts:
    - clustermanager
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_idxc_manager.yml
  vars_files:
    - ../environments/vault.yml


- hosts:
    - indexer
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_idxc_member.yml
  vars_files:
    - ../environments/vault.yml

# we are not including search head cluster servers here. They have their own playbook splunk_shc_deploy.yml
- hosts:
    - monitoringconsole
    - search 
    - licensemaster
  roles:
  - ../roles/splunk
  vars:
    - deployment_task: configure_idxc_sh.yml
  vars_files:
    - ../environments/vault.yml

## make all hosts search peers of monitoring console
- hosts:
    - monitoringconsole
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_distributed_search_peer.yml
  vars_files:
    - ../environments/vault.yml
