---
splunk_uri_lm: "https://{{ groups['licensemaster'] | first }}:8089" # need to get in list
splunk_license_group: Enterprise
license_file_dir: "{{ role_path }}/files/"
license_file_name: "Splunk.License"
license_file_path: "{{ license_file_dir }}/{{ license_file_name }}"
#splunk_uri_cm: https://new_CM1.tintin.website:8089
splunk_uri_cm: https://{{ groups['clustermanager'] | first }}:8089


splunk_admin_username: admin
splunk_admin_password: "{{ vault_splunk_admin_password }}"


# IDXC Vars
splunk_idxc_key: "{{ vault_splunk_idxc_key }}"
splunk_idxc_rf: 2
splunk_idxc_sf: 2
splunk_idxc_label: myidxc

# SHC Vars
splunk_shc_key: "{{ vault_splunk_shc_key }}"
splunk_shc_label: myshc
